export {
  round,
  clamp,
  cmToInches,
  inchesToCm,
  cmToFeetInches,
  feetInchesToCm,
  metersToCm,
  cmToMeters,
  kgToLbs,
  lbsToKg,
  kgToGrams,
  gramsToKg,
  toKg,
  toCm,
  convertUnit,
  type LengthUnit,
  type WeightUnit,
} from "./units";

export {
  calculateAge,
  calculateBmi,
  getBmiCategory,
  matchRange,
  statusToBadgeVariant,
  BMI_RANGES,
  calculateBmrMifflin,
  calculateTdee,
  ACTIVITY_MULTIPLIERS,
  caloriesToMacros,
  calculateProteinTarget,
  distributeProteinMeals,
  calculateWaterIntakeLiters,
  healthyWeightRangeKg,
  idealBodyWeightKg,
  progressPercent,
  type Sex,
  type ActivityLevel,
  type MacroSplit,
  type MacroGrams,
} from "./domain";

export {
  buildCalculatorMetadata,
  calculatorJsonLd,
  calculatorBreadcrumbJsonLd,
  calculatorFaqJsonLd,
} from "./seo";
