export {
  getProfile,
  updateProfile,
  getDailySummary,
  getMetricSeries,
  getWorkoutStreak,
  getGoals,
  createGoal,
  getWeightLogs,
  addWeightLog,
  getWorkoutLogs,
  getWaterLogs,
  addWaterLog,
  getDietLogs,
  getCalculatorHistory,
  getSavedItems,
  unsaveItem,
  getNotifications,
  markNotificationRead,
  markAllNotificationsRead,
  getRecentActivity,
  getDashboardSnapshot,
  getLatestArticlesForDashboard,
  getRecommendedWorkouts,
  getRecommendedDiets,
  getDemoUserId,
} from "./dashboard";

export {
  prismaGetProfile,
  prismaUpsertProfile,
  prismaAddWeightLog,
  prismaAddWaterLog,
  prismaAddWorkoutLog,
  prismaCreateGoal,
  prismaSaveItem,
  prismaListNotifications,
} from "./prisma-dashboard";
